version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: ../config/development/Dockerfile.server
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - BASE_URL=http://localhost:3000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/projets
      - SECRET_KEY=notsecretkey
      - OIDC_CLIENT_ID=st-projects-client
      - OIDC_CLIENT_SECRET=LCP8yqJPkXqbGwQ19V7mSw3IXtTdrGzF
      - OIDC_ENFORCED=true
      - OIDC_FULLNAME_ATTRIBUTES=given_name,usual_name
      - OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=RS256
      - OIDC_IGNORE_ROLES=true
      - OIDC_IGNORE_USERNAME=true
      - OIDC_ISSUER=http://keycloak-1:8080/realms/st-projects
      - OIDC_ROLES_ATTRIBUTE=groups
      - OIDC_SCOPES=openid profile email siret
      - OIDC_USERINFO_SIGNED_RESPONSE_ALG=RS256
      - OIDC_USE_DEFAULT_RESPONSE_MODE=true
      # - OIDC_RESPONSE_MODE=fragment
      # - OIDC_ADMIN_ROLES=admin
      # - OIDC_CLAIMS_SOURCE=userinfo
      # - OIDC_EMAIL_ATTRIBUTE=email
      # - OIDC_NAME_ATTRIBUTE=name
      # - OIDC_USERNAME_ATTRIBUTE=preferred_username
    working_dir: /app
    command: ['sh', '-c', 'npm run start']
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: ../config/development/Dockerfile.client
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - BASE_URL=http://localhost:3000
      - REACT_APP_SERVER_BASE_URL=http://localhost:3000
    working_dir: /app/client
    command: npm start

  init-db:
    build:
      context: ./server
      dockerfile: ../config/development/Dockerfile.server
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/projets
      - DEFAULT_ADMIN_EMAIL=user.test@anct.gouv.fr
      - DEFAULT_ADMIN_PASSWORD=password
      - DEFAULT_ADMIN_NAME=Test User
      - DEFAULT_ADMIN_USERNAME=test.user
    working_dir: /app
    command: ['sh', '-c', 'npm run db:init']
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: projets
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d projets']
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./config/development/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client

volumes:
  db-data:
