ARG NODE_VERSION=22.21.1

FROM node:${NODE_VERSION}-alpine AS server-dependencies

RUN apk -U upgrade \
  && apk add build-base python3 --no-cache

WORKDIR /app

COPY package.json package-lock.json .

RUN npm install
